cmake_minimum_required(VERSION 3.20)
file(READ "${PROJECT_ROOT}/docs/public-contract-v1.14.json" contract)
function(require_value expected)
    string(JSON actual GET "${contract}" ${ARGN})
    if(NOT "${actual}" STREQUAL "${expected}")
        message(FATAL_ERROR "Current contract ${ARGN}: expected ${expected}, got ${actual}")
    endif()
endfunction()
require_value("${EXPECTED_VERSION}" release engine_version)
require_value("1.14.0" release engine_version)
require_value("v1.14" release milestone)
require_value("frozen-candidate" release state)
require_value("1" c_api major)
require_value("14" c_api minor)
require_value("0" c_api patch)
require_value("14" cpp_api minor)
require_value("2" c_abi generation)
require_value("5" c_abi revision)
require_value("140" c_abi symbol_count)
require_value("${EXPECTED_VERSION}" c_abi library_version)
require_value("2" c_abi soversion)
require_value("1" cli major)
require_value("0" cli minor)
require_value("1" machine_result_protocol major)
require_value("2" machine_result_protocol minor)
require_value("20" builtin_source_contract minor)
require_value("340" builtin_source_contract descriptor_count)
require_value("342" builtin_source_contract registered_name_count)
require_value("public-contract-v1.14.json" cmake_package current_contract_file)

function(check_artifacts node)
    string(JSON type TYPE "${node}")
    if(NOT type STREQUAL "OBJECT")
        return()
    endif()
    string(JSON hash ERROR_VARIABLE no_hash GET "${node}" sha256_lf)
    if(NOT no_hash)
        string(JSON path GET "${node}" path)
        file(READ "${PROJECT_ROOT}/${path}" contents)
        string(REPLACE "\r\n" "\n" contents "${contents}")
        string(REPLACE "\r" "\n" contents "${contents}")
        string(SHA256 actual "${contents}")
        if(NOT actual STREQUAL hash)
            message(FATAL_ERROR "Current artifact hash mismatch: ${path}")
        endif()
    endif()
    string(JSON count LENGTH "${node}")
    if(count GREATER 0)
        math(EXPR last "${count} - 1")
        foreach(i RANGE 0 ${last})
            string(JSON key MEMBER "${node}" ${i})
            string(JSON child_type TYPE "${node}" "${key}")
            if(child_type STREQUAL "OBJECT")
                string(JSON child GET "${node}" "${key}")
                check_artifacts("${child}")
            endif()
        endforeach()
    endif()
endfunction()
check_artifacts("${contract}")
foreach(pair IN ITEMS "c_api;header" "cpp_api;header")
    list(GET pair 0 api)
    list(GET pair 1 field)
    string(JSON live GET "${contract}" ${api} ${field} sha256_lf)
    if(api STREQUAL "c_api")
        string(JSON snapshot GET "${contract}" c_abi snapshot sha256_lf)
    else()
        string(JSON snapshot GET "${contract}" cpp_api snapshot_header sha256_lf)
    endif()
    if(NOT live STREQUAL snapshot)
        message(FATAL_ERROR "Live and frozen ${api} headers differ")
    endif()
endforeach()
message(STATUS "MParser 1.14.0 current public contract validated")
