#include "mparser/token.h"

namespace mparser {

const char* tokenKindName(TokenKind kind) {
    switch (kind) {
    case TokenKind::EndOfFile:
        return "EndOfFile";
    case TokenKind::Newline:
        return "Newline";
    case TokenKind::Identifier:
        return "Identifier";
    case TokenKind::Number:
        return "Number";
    case TokenKind::String:
        return "String";
    case TokenKind::SystemCommand:
        return "SystemCommand";
    case TokenKind::KeywordArguments:
        return "KeywordArguments";
    case TokenKind::KeywordBreak:
        return "KeywordBreak";
    case TokenKind::KeywordCase:
        return "KeywordCase";
    case TokenKind::KeywordCatch:
        return "KeywordCatch";
    case TokenKind::KeywordClassdef:
        return "KeywordClassdef";
    case TokenKind::KeywordContinue:
        return "KeywordContinue";
    case TokenKind::KeywordElse:
        return "KeywordElse";
    case TokenKind::KeywordElseif:
        return "KeywordElseif";
    case TokenKind::KeywordEnd:
        return "KeywordEnd";
    case TokenKind::KeywordEnumeration:
        return "KeywordEnumeration";
    case TokenKind::KeywordEvents:
        return "KeywordEvents";
    case TokenKind::KeywordFor:
        return "KeywordFor";
    case TokenKind::KeywordFunction:
        return "KeywordFunction";
    case TokenKind::KeywordGlobal:
        return "KeywordGlobal";
    case TokenKind::KeywordIf:
        return "KeywordIf";
    case TokenKind::KeywordImport:
        return "KeywordImport";
    case TokenKind::KeywordMethods:
        return "KeywordMethods";
    case TokenKind::KeywordOtherwise:
        return "KeywordOtherwise";
    case TokenKind::KeywordParfor:
        return "KeywordParfor";
    case TokenKind::KeywordPersistent:
        return "KeywordPersistent";
    case TokenKind::KeywordProperties:
        return "KeywordProperties";
    case TokenKind::KeywordReturn:
        return "KeywordReturn";
    case TokenKind::KeywordSpmd:
        return "KeywordSpmd";
    case TokenKind::KeywordSwitch:
        return "KeywordSwitch";
    case TokenKind::KeywordTry:
        return "KeywordTry";
    case TokenKind::KeywordWhile:
        return "KeywordWhile";
    case TokenKind::LParen:
        return "LParen";
    case TokenKind::RParen:
        return "RParen";
    case TokenKind::LBracket:
        return "LBracket";
    case TokenKind::RBracket:
        return "RBracket";
    case TokenKind::LBrace:
        return "LBrace";
    case TokenKind::RBrace:
        return "RBrace";
    case TokenKind::Comma:
        return "Comma";
    case TokenKind::Semicolon:
        return "Semicolon";
    case TokenKind::Colon:
        return "Colon";
    case TokenKind::Dot:
        return "Dot";
    case TokenKind::DotDot:
        return "DotDot";
    case TokenKind::Ellipsis:
        return "Ellipsis";
    case TokenKind::Less:
        return "Less";
    case TokenKind::Greater:
        return "Greater";
    case TokenKind::LessEqual:
        return "LessEqual";
    case TokenKind::GreaterEqual:
        return "GreaterEqual";
    case TokenKind::Equal:
        return "Equal";
    case TokenKind::EqualEqual:
        return "EqualEqual";
    case TokenKind::NotEqual:
        return "NotEqual";
    case TokenKind::Plus:
        return "Plus";
    case TokenKind::Minus:
        return "Minus";
    case TokenKind::Star:
        return "Star";
    case TokenKind::Slash:
        return "Slash";
    case TokenKind::Backslash:
        return "Backslash";
    case TokenKind::Caret:
        return "Caret";
    case TokenKind::DotStar:
        return "DotStar";
    case TokenKind::DotSlash:
        return "DotSlash";
    case TokenKind::DotBackslash:
        return "DotBackslash";
    case TokenKind::DotCaret:
        return "DotCaret";
    case TokenKind::DotApostrophe:
        return "DotApostrophe";
    case TokenKind::Ampersand:
        return "Ampersand";
    case TokenKind::Pipe:
        return "Pipe";
    case TokenKind::DoubleAmpersand:
        return "DoubleAmpersand";
    case TokenKind::DoublePipe:
        return "DoublePipe";
    case TokenKind::Tilde:
        return "Tilde";
    case TokenKind::Apostrophe:
        return "Apostrophe";
    case TokenKind::At:
        return "At";
    case TokenKind::Question:
        return "Question";
    case TokenKind::Unknown:
        return "Unknown";
    }
    return "Unknown";
}

const char* triviaKindName(TriviaKind kind) {
    switch (kind) {
    case TriviaKind::Whitespace:
        return "Whitespace";
    case TriviaKind::LineComment:
        return "LineComment";
    case TriviaKind::BlockComment:
        return "BlockComment";
    }
    return "Unknown";
}

} // namespace mparser
